spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://sebas9:Halamadrid10@cluster0.2u8mg.mongodb.net/purely_auth_service?retryWrites=true&w=majority&appName=Cluster0

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
